### ISSUE TITLE
‘codigos_municipios’ not found

### ISSUE THREAD

**Issue by paugrau** [meneos/elecciones#10]
When trying to download data I get the following error: 

`mun_2019 <- infoelectoral::mesas(tipo_eleccion = "municipales", anno = "2019", mes="05")`

```
trying URL 'https://infoelectoral.interior.gob.es/estaticos/docxl/apliextr/04201905_MESA.zip'
Content type 'application/zip' length 8573678 bytes (8.2 MB)
==================================================
downloaded 8.2 MB

Error in fix.by(by.y, y) : 'by' must specify uniquely valid columns
In addition: Warning message:
In data("codigos_municipios", envir = environment()) :
  data set ‘codigos_municipios’ not found
```

I guess it has to do with a change from the source of the data. I tried to debug it myself but couldn't find where the function "read09" comes from (necessary to run `dfbasicos <- read09(xbasicos, tempd)`, inside the `mesas` function).

Thank you for building and mantaining such a great package!

**Comment by hmeleiro** [comment]
Try to load the library instead of using the functions through the `::` method. 

I'm not sure why, but when the package is not loaded the internal dataset called `codigos_municipios` is not accesible. I have to look in to that issue.

**Comment by paugrau** [comment]
Thank you! Works perfectly once the package is loaded.

**Comment by paugrau** [comment]
Thank you! Works perfectly once the package is loaded.

**Comment by hmeleiro** [comment]
You are welcome. 

I don't really think this is the way the data is supposed to work in a package, so I'm going to keep this issue open until I solve it. I believe that the solution to this behaviour can be found [here](https://coolbutuseless.github.io/2018/12/10/r-packages-internal-and-external-data/). I'l take a look in to it.

**Comment by hmeleiro** [comment]
I think I solved this issue using the `::` method to access the external data. I think it works but if you could reinstall and check it we be awesome. 

I also implemented a minor change from `merge()` to `dplyr`'s `*_join()`. Now the package functions are much faster, especially `mesas()`.
