### ISSUE TITLE
Shapefile secciones

### ISSUE THREAD

**Issue by Aimonius** [meneos/elecciones#2]
Buenas tardes. En primer lugar enhorabuena por el trabajo. Estoy intentando replicar el ejemplo en [tu página](https://htmlpreview.github.io/?https://raw.githubusercontent.com/meneos/elecciones/master/vignettes/Ejemplo.html) pero no dispongo del shapefile de las secciones que mencionas en el mismo. Al intentar hacerlo con otra localidad de la que si tengo las secciones no me las encuentra. ¿Como debo 'arreglar' las secciones para que coincidan con los datos descargados? 
Gracias anticipadas.

**Comment by Aimonius** [comment]
Perdona la insistencia. Sigo con mi intento de replicar tu ejemplo para aplicarlo en un par de provincias, pero me encuentro estos errores: 
Este primero ocurre al importar el shapefile, supongo que es porque no tengo el geocodigo (no lo veo en la tabla de atributos del shp).
```
Warning messages:
1: Unknown or uninitialised column: 'GEOCODIGO'. 
2: Length of logical index must be 1 or 4272, not 0 
```
Aún así, saca los resultados de los cinco partidos, pero al fusionar los datos con el shapefile, me salta este nuevo error, derivado supongo del anterior:
```
> seccs.muni$GEOCODIGO <- paste0(seccs.muni$municipio, seccs.muni$distrito, seccs.muni$seccion)
> 
> shp <- merge(shp, seccs.muni, by = "GEOCODIGO")
Error in fix.by(by.x, x) : 'by' must specify a uniquely valid column
```
Y claro, la visualización ya no funciona.
¿Cómo puedo obtener el geocódigo? Supongo que es la corrección que has hecho al shape, pero no intuyo como obtenerlo.
Gracias de nuevo por tu atención.

**Comment by hmeleiro** [comment]
El GEOCODIGO es como se llama una de las columnas del shapefile de la Comunidad de Madrid que uso en el ejemplo. Es la combinación del código del municipio, del distritos y de la sección censal. No hace falta que fusiones en base a esa columna en concreto, valdría con otra que tenga tu shapefile y que tenga valores únicos para cada sección censal.

¿Qué shapefile estás usando? ¿Hay alguna columna con ids de las secciones censales? Tienes que tratar de reconstruirla en el data frame de los resultados.

**Comment by Aimonius** [comment]
Estoy usando un shapefile de Madrid que saque del Instituto Nacional de Estadística (INE), son las secciones censales de 2014, pero para poder replicar tu ejemplo y entender el mecanismo me vale. Lo voy a replicar con algunos municipios de la provincia de León. El shp tiene un CUSECC que podría valer, miraré si lo tienen los resultados del ministerio.

**Comment by hmeleiro** [comment]
Creo recordar que esa columna es la combinación de provincia+municipio+distrito+seccion. 

Prueba a hacerlo así.

Agrupalos poniendo la columna provincia (para que no se pierda en el proceso):
```
# Agrupo los datos
seccs.muni <- results.muni %>% 
  group_by(year, mes, provincia, municipio, distrito, seccion, siglas) %>% 
  summarise(censo = sum(censo.INE), 
            votos.candidatura = sum(candidaturas), 
            votos = sum(votos))
```

Y luego al crear la columna antes de fusionar añadele el código de la provincia. Tal que así:
```
seccs.muni$GEOCODIGO <- paste0(seccs.muni$provincia, seccs.muni$municipio, seccs.muni$distrito, seccs.muni$seccion)

```

**Comment by Aimonius** [comment]
Al introducir esas nuevas lineas con el shape de Madrid me da estos dos errores, además del primero anterior:
```
> shp <- merge(shp, seccs.muni, by = "GEOCODIGO")
Error in fix.by(by.x, x) : 'by' must specify a uniquely valid column
```

```
> mapa
Error in if (diff(xlim) == 0 || diff(ylim) == 0) { : 
  valor ausente donde TRUE/FALSE es necesario
```

**Comment by hmeleiro** [comment]
No has debido crear correctamente la columna o no estás usando la función merge correcta. Asegúrate de estar usando la función correcta llamándola así: ```sp::merge()```

De todas formas, esto no es un problema de la librería así que cierro el issue y lo hablamos por email.
