### ISSUE TITLE
Error en instalación del paquete "elecciones" 

### ISSUE THREAD

**Issue by grial** [meneos/elecciones#3]
Hola. En la instalación del paquete "elecciones" me aparece este error: 

Warning in install.packages :
  package ‘elecciones’ is not available (for R version 3.5.2)

sysname           release           version          nodename
        "Windows"        ">= 8 x64"      "build 9200"

No sé si tiene alguna relación, pero cuando instalo devtools me da problemas la instalación del paquete "rcmdckeck" y sale este mensaje: 

installing the source package ‘rcmdcheck’

trying URL 'https://cran.rstudio.com/src/contrib/rcmdcheck_1.3.2.tar.gz'
Content type 'application/x-gzip' length 1408582 bytes (1.3 MB)
downloaded 1.3 MB

* installing *source* package 'rcmdcheck' ...
** package 'rcmdcheck' successfully unpacked and MD5 sums checked
Error in file(file, if (append) "a" else "w") : 
  (convertido del aviso) cannot open file 'C:/Users/Marma/Documents/R/win-library/3.5/rcmdcheck/DESCRIPTION': No such file or directory
ERROR: installing package DESCRIPTION failed for package 'rcmdcheck'
* removing 'C:/Users/María/Documents/R/win-library/3.5/rcmdcheck'
* restoring previous 'C:/Users/María/Documents/R/win-library/3.5/rcmdcheck'
In R CMD INSTALL
Error in i.p(...) : 
  (converted from warning) installation of package ‘rcmdcheck’ had non-zero exit status

Muchas gracias.

**Comment by hmeleiro** [comment]
¿Qué comando has introducido para instalar la librería? ¿Puede ser que hayas escrito ```install.packages("elecciones")``` en vez de ```devtools::install_github("hmeleiro/elecciones")```?

**Comment by grial** [comment]
Hola. Introduje devtools::install_github("hmeleiro/elecciones") . Conseguí instalarlo perfectamente en otro ordenador, así que trabajaré los datos con el otro. 
Muchas gracias por el paquete y por las instrucciones. Son muy útiles y facilitan mucho el trabajo.

Un saludo.

**Comment by hmeleiro** [comment]
Gracias a ti! me alegro que sea útil.

Igualmente, me interesa profundizar en ese error. ¿Has probado a instalar la librería ```rcmdcheck``` por separado para luego volver a instalar ```devtools```? ¿Tienes todos los paquetes y librerías actualizadas?

He hecho un commit especificando que la librería depende de R (>= 3.1.0) a ver si así te deja. También he aprovechado y he eliminado algunas dependencias innecesarias por si acaso era ese el problema.

¿Podrías volver a intentarlo en el ordenador en el que te daba el error?

**Comment by grial** [comment]
Hola. Sí, sí, probé a instalar rcmdcheck por separado y, en teoría sí tengo actualizados los paquetes. En cuanto pueda vuelvo a probarlo en donde no funcionaba. 

Gracias.

**Comment by edugonzaloalmorox** [comment]
Hola, 

Muchas gracias por desarrollar el paquete, super útil en estos tiempos de comicios. Estoy intentando replicar los ejemplos de las funciones `mesas()` y `municipios()` y en ambos me aparece el siguiente error:

```
results.muni <- mesas("municipales", "2015", "05")
trying URL 'http://www.infoelectoral.mir.es/infoelectoral/docxl/apliextr/04201505_MESA.zip'
Content type 'application/zip' length 9794107 bytes (9.3 MB)
==================================================
downloaded 9.3 MB

Error in date_names_lang(date_names) : 
  lazy-load database 'MyComputer/Library/R/3.4/library/readr/R/sysdata.rdb' is corrupt
In addition: Warning messages:
1: In date_names_lang(date_names) :
  restarting interrupted promise evaluation
2: In date_names_lang(date_names) : internal error -5 in R_decompress1
```
Muchas gracias!

**Comment by hmeleiro** [comment]
Hola @edugonzaloalmorox,

en mis ordenadores funciona todo correctamente. No soy capaz de reproducir el error. Parece que el fallo tiene que ver con ```readr```. ¿Tienes su ultima versión? ¿Podrías probar a desinstalar y volver a instalar tanto ```readr``` como ```elecciones```?

Gracias!

**Comment by edugonzaloalmorox** [comment]
Perfecto, ahora funciona. Gracias @hmeleiro !

**Comment by hmeleiro** [comment]
Genial! Cierro el issue.

**Comment by acaymoviera** [comment]
Hola, Héctor. 

Estoy realizando un artículo sobre elecciones y me gustaría utilizar el tutorial que tenía sobre mapas para poder plasmar los análisis. No sé si es posible recuperarlo, ya que era de gran utilidad. 

Muchas gracias por tu labor!

**Comment by hmeleiro** [comment]
Hola @acaymoviera, ¿te refieres a [este](https://ropenspain.github.io/infoelectoral/articles/municipios.html)?
