### ISSUE TITLE
Los datos descargados por mesa de elecciones generales 2016 están incompletos

### ISSUE THREAD

**Issue by numeroteca** [meneos/elecciones#4]
Me he dado cuenta de que no tengo, por ejemplo, la ciudad de Albacete ¿podéis probar si os pasa lo mismo?
`download_mesas(tipoeleccion = "generales", yr = 2016, mes = "06", dir = "data/original")`

**Comment by hmeleiro** [comment]
Hola numeroteca,

a mi sí me aparecen los de Albacete. El código INE de este municipio es el 02003, así que el siguiente código te los debería mostrar.

```
x %>% 
  filter(provincia == 2 & municipio == "003") %>% 
  group_by(denominacion) %>% 
  summarise(votos = sum(votos)) %>% 
  arrange(-votos)

# A tibble: 9 x 2
  denominacion                                 votos
  <chr>                                        <dbl>
1 PARTIDO POPULAR                              38470
2 PARTIDO SOCIALISTA OBRERO ESPAÑOL            20846
3 CIUDADANOS-PARTIDO DE LA CIUDADANÍA          17378
4 UNIDOS PODEMOS                               16193
5 PARTIDO ANIMALISTA CONTRA EL MALTRATO ANIMAL  1055
6 UNIÓN PROGRESO Y DEMOCRACIA                    233
7 RECORTES CERO-GRUPO VERDE                      183
8 FALANGE ESPAÑOLA DE LAS JONS                   121
9 PARTIDO COMUNISTA DE LOS PUEBLOS DE ESPAÑA     108
```

Estos resultados corresponden a estos de aquí:

https://resultados.elpais.com/elecciones/2016/generales/congreso/07/02/03.html

Un saludo y cierro issue. Si tienes algún otro problema dime.
