### ISSUE TITLE
No funciona para las elecciones del 10N

### ISSUE THREAD

**Issue by Wolbyworld** [meneos/elecciones#5]
Las elecciones del 10N no están funcionando. No soy capaz de encontrarlas en el Ministerio de Interior tampoco, pero no sé si es que han cambiado el formato de la URL.

**Comment by hmeleiro** [comment]
Hola Wolbyworld, perdona que haya tardado tanto en contestar, pero no suelo estar muy pendiente de esto. No se trata de ningún issue, es que el Ministerio del Interior tarda unos meses en subir los datos definitivos. Ya están disponibles desde hace unas semanas y por lo que he podido comprobar la librería sigue funcionando.

Un saludo, y cierro el issue.
