### ISSUE TITLE
Nuevas url: url no disponible

### ISSUE THREAD

**Issue by dieghernan** [meneos/elecciones#7]
Buenas, veo que has actualizado las urls del proyecto en 5c51a45fc2e13f506e83eedeb4a64a21d3fe9d15

Comentarte que he pasado la función `urlchecker::url_check()` para comprobar las urls y me sale este mensaje:

```
x Error: man/codigos_ccaa.Rd:16:6 404: Not Found
\url{http://www.infoelectoral.mir.es/infoelectoral/min/areaDescarga.html?method=inicio}
```

https://github.com/rOpenSpain/infoelectoral/blob/5c51a45fc2e13f506e83eedeb4a64a21d3fe9d15/R/data.R#L26

Parece que esta url ya no está disponible: http://www.infoelectoral.mir.es/infoelectoral/min/areaDescarga.html?method=inicio,

¿Quizá haya que actualizarla con esta: https://infoelectoral.interior.gob.es/opencms/es/elecciones-celebradas/area-de-descargas/?

O si viene del INE: https://www.ine.es/daco/daco42/codmun/cod_ccaa.htm

**Comment by hmeleiro** [comment]
¡Cierto! Ayer corregí las urls en las funciones pero se me olvidó revisar la documentación. Solucionado con [`5c51a45`](https://github.com/rOpenSpain/infoelectoral/commit/5c51a45fc2e13f506e83eedeb4a64a21d3fe9d15).

Gracias por el aviso.
